cabal-version:      3.0
name:               df
version:            0.1.0.0
synopsis:           Apache Arrow Bindings
homepage:           https://github.com/ih1d/mpl
author:             Isaac Hiram Lopez Diaz
maintainer:         isaac.lopez@upr.edu
category:           Data
build-type:         Simple

common warnings
    ghc-options:
        -Wall
        -Wcompat
        -Widentities
        -Wincomplete-record-updates
        -Wincomplete-uni-patterns
        -Wmissing-home-modules
        -Wredundant-constraints
        -Wunused-packages

library
    import:           warnings
    exposed-modules:  Dataframe
    build-depends:    base ^>=4.18.3.0
    hs-source-dirs:   src
    default-language: GHC2021
    pkgconfig-depends:
        arrow-glib
    include-dirs:     cbits
    c-sources:        cbits/mpl_runtime.c
                    , cbits/mpl_runtime.h