cabal-version:      3.0
name:               mpl-core
version:            0.1.0.0
synopsis:           A Programming Language with Algebraic Effects for Dataframes
author:             Isaac Hiram Lopez Diaz
maintainer:         isaac.lopez@upr.edu
category:           Language
build-type:         Simple

common warnings
    ghc-options:
        -Wall
        -Wcompat
        -Widentities
        -Wincomplete-record-updates
        -Wincomplete-uni-patterns
        -Wmissing-home-modules
        -Wredundant-constraints
        -Wunused-packages

library
    import:           warnings
    default-extensions:
        OverloadedStrings
        ImportQualifiedPost
    other-modules:
        Plan.Monad
    exposed-modules:
        Parser
        Syntax
        Lexer
        MPLTypes
        Dataframe
    build-depends:    base   ^>=4.18.3.0
                    , parsec
                    , vector
                    , freer-simple
    hs-source-dirs:   src
    default-language: GHC2021
    pkgconfig-depends:
        arrow-glib
    include-dirs:     cbits
    c-sources:        cbits/runtime.c