name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fourmolu:
    name: Fourmolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "0.16.2.0"
          pattern: |
            src/**/*.hs
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/hlint-setup@v2
        with:
          version: "3.8"

      - uses: haskell-actions/hlint-run@v2
        with:
          path: '["src"]'
          fail-on: warning
